services:
  aodt-server:
    container_name: aodt-server
    restart: unless-stopped
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${AODT_AGENT_PUBLIC_PORT:-8082}:5000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
